In [91]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

In [92]:
ZF=pd.read_csv('/content/Z,F_2_csv.csv', encoding='cp949') #데이터
ZF

              구분      년도  ...     2020.12                  2020.13
0            NaN      항목  ...  유동비율(IFRS)  * 발행한 주식총수(*)(IFRS)(천원)
1            회사명   거래소코드  ...      amount                   amount
2     (주)BNK금융지주  138930  ...         NaN                      NaN
3       (주)DB하이텍     990  ...      174.09                 44511167
4      (주)KB금융지주  105560  ...         NaN                      NaN
..           ...     ...  ...         ...                      ...
198     현대자동차(주)    5380  ...      138.98                276939058
199      현대제철(주)    4020  ...      152.73                133445785
200   현대중공업지주(주)  267250  ...       67.66                 15798617
201  현대해상화재보험(주)    1450  ...         NaN                      NaN
202       휴켐스(주)   69260  ...      442.53                 40878588

[203 rows x 30 columns]

In [93]:
ZF.info() #데이터 정보

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 30 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   구분       202 non-null    object
 1   년도       203 non-null    object
 2   2019     184 non-null    object
 3   2019.1   184 non-null    object
 4   2019.2   184 non-null    object
 5   2019.3   184 non-null    object
 6   2019.4   184 non-null    object
 7   2019.5   184 non-null    object
 8   2019.6   184 non-null    object
 9   2019.7   184 non-null    object
 10  2019.8   184 non-null    object
 11  2019.9   184 non-null    object
 12  2019.10  184 non-null    object
 13  2019.11  183 non-null    object
 14  2019.12  183 non-null    object
 15  2019.13  184 non-null    object
 16  2020     184 non-null    object
 17  2020.1   184 non-null    object
 18  2020.2   184 non-null    object
 19  2020.3   184 non-null    object
 20  2020.4   184 non-null    object
 21  2020.5   184 non-null    object
 22  2020.6   184 non-null    object
 23  2020.7   184 non-null    object
 24  2020.8   184 non-null    object
 25  2020.9   184 non-null    object
 26  2020.10  184 non-null    object
 27  2020.11  184 non-null    object
 28  2020.12  184 non-null    object
 29  2020.13  184 non-null    object
dtypes: object(30)
memory usage: 47.7+ KB

In [94]:
ZF.isnull().sum() #결측치 확인

구분          1
년도          0
2019       19
2019.1     19
2019.2     19
2019.3     19
2019.4     19
2019.5     19
2019.6     19
2019.7     19
2019.8     19
2019.9     19
2019.10    19
2019.11    20
2019.12    20
2019.13    19
2020       19
2020.1     19
2020.2     19
2020.3     19
2020.4     19
2020.5     19
2020.6     19
2020.7     19
2020.8     19
2020.9     19
2020.10    19
2020.11    19
2020.12    19
2020.13    19
dtype: int64

In [95]:
ZF_2 = ZF_1.dropna(axis=0) #결측치항 제거
ZF_2

             구분   거래소코드     자산(2019)  ... 부채비율(2020) 유동비율(2020) 발행한 주식총수(2020)
1           회사명   거래소코드       amount  ...     amount     amount         amount
3      (주)DB하이텍     990   1089400761  ...      48.29     174.09       44511167
5       (주)강원랜드   35250   4436461953  ...      12.06     452.28      213940500
6      (주)남선알미늄    8350    292559970  ...       59.1      190.3      110486980
7        (주)녹십자    6280   1742374171  ...       69.3     188.14       11686538
..          ...     ...          ...  ...        ...        ...            ...
197     현대위아(주)   11210   5791649000  ...      90.98     212.45       27195083
198    현대자동차(주)    5380  74157219000  ...      46.77     138.98      276939058
199     현대제철(주)    4020  32025224295  ...      97.85     152.73      133445785
200  현대중공업지주(주)  267250   8583906445  ...      39.67      67.66       15798617
202      휴켐스(주)   69260    893230019  ...      26.79     442.53       40878588

[182 rows x 30 columns]

In [96]:
# 열 이름 변경
ZF_1 = ZF.rename(columns = {"년도":"거래소코드",
                            "2019": "자산(2019)", 
	                          "2019.1" : "유동자산(2019)",
                            "2019.2" : "유동부채(2019)",
                            "2019.3" : "이익잉여금(결손금)(2019)",
                            "2019.4" : "매출액(수익)(2019)",	
                            "2019.5" :	"매출원가(2019",
                            "2019.6" : "판매비와 관리비(물류원가 등 포함)(2019)",
                            "2019.7" : "자본(2019)",
                            "2019.8" : "부채(2019)",
                            "2019.9" : "당기순이익(2019)",
                            "2019.10" : "영업활동으로 인한 현금흐름(간접법)(2019)",
                            "2019.11" : "부채비율(2019)",
                            "2019.12" : "유동비율(2019)",
                            "2019.13" : "발행한 주식총수(2019)",
                            "2020" :  "자산(2020)",	
                            "2020.1" : "유동자산(2020)",
                            "2020.2" :	"유동부채(2019)",
                            "2020.3" :	"이익잉여금(결손금)(2020)",
                            "2020.4" : "매출액(수익)(2020)",	
                            "2020.5" : "매출원가(2020)",
                            "2020.6" :	"판매비와 관리비(물류원가 등 포함)(2020)",
                            "2020.7" : "자본(2020)",
                            "2020.8" : "부채(2020)",
                            "2020.9" : "당기순이익(2020)",
                            "2020.10" : "영업활동으로 인한 현금흐름(간접법)(2020)",
                            "2020.11" : "부채비율(2020)",
                            "2020.12" : "유동비율(2020)",
                            "2020.13" : "발행한 주식총수(2020)"},
                            )

In [97]:
ZF_1 # 열 이름 변경 확인

              구분   거래소코드  ...  유동비율(2020)           발행한 주식총수(2020)
0            NaN      항목  ...  유동비율(IFRS)  * 발행한 주식총수(*)(IFRS)(천원)
1            회사명   거래소코드  ...      amount                   amount
2     (주)BNK금융지주  138930  ...         NaN                      NaN
3       (주)DB하이텍     990  ...      174.09                 44511167
4      (주)KB금융지주  105560  ...         NaN                      NaN
..           ...     ...  ...         ...                      ...
198     현대자동차(주)    5380  ...      138.98                276939058
199      현대제철(주)    4020  ...      152.73                133445785
200   현대중공업지주(주)  267250  ...       67.66                 15798617
201  현대해상화재보험(주)    1450  ...         NaN                      NaN
202       휴켐스(주)   69260  ...      442.53                 40878588

[203 rows x 30 columns]

In [98]:
ZF_3 = ZF_2.drop(ZF_2.index[0]) # 인덱스 0번째항 제거
ZF_3

             구분   거래소코드     자산(2019)  ... 부채비율(2020) 유동비율(2020) 발행한 주식총수(2020)
3      (주)DB하이텍     990   1089400761  ...      48.29     174.09       44511167
5       (주)강원랜드   35250   4436461953  ...      12.06     452.28      213940500
6      (주)남선알미늄    8350    292559970  ...       59.1      190.3      110486980
7        (주)녹십자    6280   1742374171  ...       69.3     188.14       11686538
8     (주)녹십자홀딩스    5250    928991658  ...      71.31      32.24       49543070
..          ...     ...          ...  ...        ...        ...            ...
197     현대위아(주)   11210   5791649000  ...      90.98     212.45       27195083
198    현대자동차(주)    5380  74157219000  ...      46.77     138.98      276939058
199     현대제철(주)    4020  32025224295  ...      97.85     152.73      133445785
200  현대중공업지주(주)  267250   8583906445  ...      39.67      67.66       15798617
202      휴켐스(주)   69260    893230019  ...      26.79     442.53       40878588

[181 rows x 30 columns]

In [99]:
ZF_3.info() # 데이터 정보 재확인

<class 'pandas.core.frame.DataFrame'>
Int64Index: 181 entries, 3 to 202
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   구분                         181 non-null    object
 1   거래소코드                      181 non-null    object
 2   자산(2019)                   181 non-null    object
 3   유동자산(2019)                 181 non-null    object
 4   유동부채(2019)                 181 non-null    object
 5   이익잉여금(결손금)(2019)           181 non-null    object
 6   매출액(수익)(2019)              181 non-null    object
 7   매출원가(2019                  181 non-null    object
 8   판매비와 관리비(물류원가 등 포함)(2019)  181 non-null    object
 9   자본(2019)                   181 non-null    object
 10  부채(2019)                   181 non-null    object
 11  당기순이익(2019)                181 non-null    object
 12  영업활동으로 인한 현금흐름(간접법)(2019)  181 non-null    object
 13  부채비율(2019)                 181 non-null    object
 14  유동비율(2019)                 181 non-null    object
 15  발행한 주식총수(2019)             181 non-null    object
 16  자산(2020)                   181 non-null    object
 17  유동자산(2020)                 181 non-null    object
 18  유동부채(2019)                 181 non-null    object
 19  이익잉여금(결손금)(2020)           181 non-null    object
 20  매출액(수익)(2020)              181 non-null    object
 21  매출원가(2020)                 181 non-null    object
 22  판매비와 관리비(물류원가 등 포함)(2020)  181 non-null    object
 23  자본(2020)                   181 non-null    object
 24  부채(2020)                   181 non-null    object
 25  당기순이익(2020)                181 non-null    object
 26  영업활동으로 인한 현금흐름(간접법)(2020)  181 non-null    object
 27  부채비율(2020)                 181 non-null    object
 28  유동비율(2020)                 181 non-null    object
 29  발행한 주식총수(2020)             181 non-null    object
dtypes: object(30)
memory usage: 43.8+ KB

In [100]:
ZF_3.set_index('구분', inplace=True )
ZF_3 = ZF_3.astype('float')
ZF_3.reset_index(inplace=True )
ZF_3

             구분     거래소코드      자산(2019)  ...  부채비율(2020)  유동비율(2020)  발행한 주식총수(2020)
0      (주)DB하이텍     990.0  1.089401e+09  ...       48.29      174.09      44511167.0
1       (주)강원랜드   35250.0  4.436462e+09  ...       12.06      452.28     213940500.0
2      (주)남선알미늄    8350.0  2.925600e+08  ...       59.10      190.30     110486980.0
3        (주)녹십자    6280.0  1.742374e+09  ...       69.30      188.14      11686538.0
4     (주)녹십자홀딩스    5250.0  9.289917e+08  ...       71.31       32.24      49543070.0
..          ...       ...           ...  ...         ...         ...             ...
176     현대위아(주)   11210.0  5.791649e+09  ...       90.98      212.45      27195083.0
177    현대자동차(주)    5380.0  7.415722e+10  ...       46.77      138.98     276939058.0
178     현대제철(주)    4020.0  3.202522e+10  ...       97.85      152.73     133445785.0
179  현대중공업지주(주)  267250.0  8.583906e+09  ...       39.67       67.66      15798617.0
180      휴켐스(주)   69260.0  8.932300e+08  ...       26.79      442.53      40878588.0

[181 rows x 30 columns]

In [105]:
ZF_4 = ZF_3.astype({'거래소코드':'int'})
ZF_4

             구분   거래소코드      자산(2019)  ...  부채비율(2020)  유동비율(2020)  발행한 주식총수(2020)
0      (주)DB하이텍     990  1.089401e+09  ...       48.29      174.09      44511167.0
1       (주)강원랜드   35250  4.436462e+09  ...       12.06      452.28     213940500.0
2      (주)남선알미늄    8350  2.925600e+08  ...       59.10      190.30     110486980.0
3        (주)녹십자    6280  1.742374e+09  ...       69.30      188.14      11686538.0
4     (주)녹십자홀딩스    5250  9.289917e+08  ...       71.31       32.24      49543070.0
..          ...     ...           ...  ...         ...         ...             ...
176     현대위아(주)   11210  5.791649e+09  ...       90.98      212.45      27195083.0
177    현대자동차(주)    5380  7.415722e+10  ...       46.77      138.98     276939058.0
178     현대제철(주)    4020  3.202522e+10  ...       97.85      152.73     133445785.0
179  현대중공업지주(주)  267250  8.583906e+09  ...       39.67       67.66      15798617.0
180      휴켐스(주)   69260  8.932300e+08  ...       26.79      442.53      40878588.0

[181 rows x 30 columns]

In [103]:
ZF_4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181 entries, 0 to 180
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   구분                         181 non-null    object
 1   거래소코드                      181 non-null    int64
 2   자산(2019)                   181 non-null    float64
 3   유동자산(2019)                 181 non-null    float64
 4   유동부채(2019)                 181 non-null    float64
 5   이익잉여금(결손금)(2019)           181 non-null    float64
 6   매출액(수익)(2019)              181 non-null    float64
 7   매출원가(2019                  181 non-null    float64
 8   판매비와 관리비(물류원가 등 포함)(2019)  181 non-null    float64
 9   자본(2019)                   181 non-null    float64
 10  부채(2019)                   181 non-null    float64
 11  당기순이익(2019)                181 non-null    float64
 12  영업활동으로 인한 현금흐름(간접법)(2019)  181 non-null    float64
 13  부채비율(2019)                 181 non-null    float64
 14  유동비율(2019)                 181 non-null    float64
 15  발행한 주식총수(2019)             181 non-null    float64
 16  자산(2020)                   181 non-null    float64
 17  유동자산(2020)                 181 non-null    float64
 18  유동부채(2019)                 181 non-null    float64
 19  이익잉여금(결손금)(2020)           181 non-null    float64
 20  매출액(수익)(2020)              181 non-null    float64
 21  매출원가(2020)                 181 non-null    float64
 22  판매비와 관리비(물류원가 등 포함)(2020)  181 non-null    float64
 23  자본(2020)                   181 non-null    float64
 24  부채(2020)                   181 non-null    float64
 25  당기순이익(2020)                181 non-null    float64
 26  영업활동으로 인한 현금흐름(간접법)(2020)  181 non-null    float64
 27  부채비율(2020)                 181 non-null    float64
 28  유동비율(2020)                 181 non-null    float64
 29  발행한 주식총수(2020)             181 non-null    float64
dtypes: float64(28), int64(1), object(1)
memory usage: 42.5+ KB