In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/상폐.csv', encoding='cp949')
df

           회사명  거래소코드  ... * 주당 액면가액(IFRS)(천원)  상장폐지일
0     (주)DB하이텍    990  ...              5000.0    NaN
1     (주)DB하이텍    990  ...              5000.0    NaN
2     (주)DB하이텍    990  ...              5000.0    NaN
3     (주)DB하이텍    990  ...              5000.0    NaN
4     (주)DB하이텍    990  ...              5000.0    NaN
...        ...    ...  ...                 ...    ...
7450   흥아해운(주)   3280  ...               500.0    NaN
7451   흥아해운(주)   3280  ...               500.0    NaN
7452   흥아해운(주)   3280  ...               500.0    NaN
7453   흥아해운(주)   3280  ...               500.0    NaN
7454   흥아해운(주)   3280  ...               500.0    NaN

[7455 rows x 7 columns]

In [ ]:
df.isnull().sum()

회사명                           0
거래소코드                         0
회계년도                          0
자산(*)(천원)                    39
* 발행한 주식총수(*)(IFRS)(천원)     170
* 주당 액면가액(IFRS)(천원)         170
상장폐지일                      7173
dtype: int64

In [ ]:
df_1=df.dropna(axis=0)
df_1

            회사명   거래소코드  ... * 주당 액면가액(IFRS)(천원)       상장폐지일
284      (주)넥솔론  110570  ...               500.0  2017/04/17
285      (주)넥솔론  110570  ...               500.0  2017/04/17
286      (주)넥솔론  110570  ...               500.0  2017/04/17
287      (주)넥솔론  110570  ...               500.0  2017/04/17
288      (주)넥솔론  110570  ...               500.0  2017/04/17
...         ...     ...  ...                 ...         ...
7358   현대페인트(주)   11720  ...               500.0  2016/11/21
7359  현대하이스코(주)   10520  ...              5000.0  2015/07/15
7360  현대하이스코(주)   10520  ...              5000.0  2015/07/15
7361  현대하이스코(주)   10520  ...              5000.0  2015/07/15
7362  현대하이스코(주)   10520  ...              5000.0  2015/07/15

[268 rows x 7 columns]

In [ ]:
df_2=df_1.drop_duplicates(['회사명'],keep='last')
df_2

             회사명   거래소코드  ... * 주당 액면가액(IFRS)(천원)       상장폐지일
289       (주)넥솔론  110570  ...               500.0  2017/04/17
381      (주)다함이텍    9280  ...              5000.0  2013/04/16
427    (주)대성합동지주    5620  ...              5000.0  2017/08/25
499     (주)대한은박지    7480  ...               500.0  2013/01/28
636      (주)동성화학    5190  ...              1000.0  2021/04/16
...          ...     ...  ...                 ...         ...
7017  한솔아트원제지(주)    7190  ...              1000.0  2017/03/15
7095     한일건설(주)    6440  ...              5000.0  2013/04/16
7183  한화화인케미칼(주)   25850  ...              5000.0  2016/03/15
7358    현대페인트(주)   11720  ...               500.0  2016/11/21
7362   현대하이스코(주)   10520  ...              5000.0  2015/07/15

[62 rows x 7 columns]

In [ ]:
df_2['시총']=df_2['* 발행한 주식총수(*)(IFRS)(천원)']*df_2['* 주당 액면가액(IFRS)(천원)']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
df_3=df_2
df_3

             회사명   거래소코드  ...       상장폐지일            시총
289       (주)넥솔론  110570  ...  2017/04/17  8.058510e+10
381      (주)다함이텍    9280  ...  2013/04/16  1.993246e+10
427    (주)대성합동지주    5620  ...  2017/08/25  8.995385e+09
499     (주)대한은박지    7480  ...  2013/01/28  3.094793e+10
636      (주)동성화학    5190  ...  2021/04/16  5.335564e+09
...          ...     ...  ...         ...           ...
7017  한솔아트원제지(주)    7190  ...  2017/03/15  3.896830e+10
7095     한일건설(주)    6440  ...  2013/04/16  1.721148e+11
7183  한화화인케미칼(주)   25850  ...  2016/03/15  1.900000e+10
7358    현대페인트(주)   11720  ...  2016/11/21  1.630633e+10
7362   현대하이스코(주)   10520  ...  2015/07/15  4.010000e+11

[62 rows x 8 columns]

In [ ]:
df_4 = df_3.sort_values(by='시총' ,ascending=False)
df_4

            회사명   거래소코드     회계년도  ...  * 주당 액면가액(IFRS)(천원)       상장폐지일            시총
3058    (주)한진해운  117930  2014/12  ...               5000.0  2017/03/07  1.226320e+12
4199    두산건설(주)   11160  2012/12  ...               5000.0  2020/03/24  8.673351e+11
4695    삼성물산(주)     830  2011/12  ...               5000.0  2015/09/15  8.043321e+11
2561  (주)케이피케미칼   64420  2011/12  ...               5000.0  2013/01/15  4.916889e+11
7362  현대하이스코(주)   10520  2011/12  ...               5000.0  2015/07/15  4.010000e+11
...         ...     ...      ...  ...                  ...         ...           ...
1013    (주)삼양엔텍    8720  2011/12  ...               5000.0  2014/12/30  6.177600e+09
636     (주)동성화학    5190  2020/12  ...               1000.0  2021/04/16  5.335564e+09
1297  (주)신성에프에이  104120  2011/12  ...                500.0  2017/01/02  4.407250e+09
1311   (주)신성이엔지  104110  2011/12  ...                500.0  2017/01/02  4.407250e+09
6287   케이비물산(주)    8540  2011/01  ...                500.0  2012/06/08  3.042917e+09

[62 rows x 8 columns]

In [ ]:
df_5=df_4.append(df_4, ignore_index = True)
df_5

           회사명   거래소코드     회계년도  ...  * 주당 액면가액(IFRS)(천원)       상장폐지일            시총
0      (주)한진해운  117930  2014/12  ...               5000.0  2017/03/07  1.226320e+12
1      두산건설(주)   11160  2012/12  ...               5000.0  2020/03/24  8.673351e+11
2      삼성물산(주)     830  2011/12  ...               5000.0  2015/09/15  8.043321e+11
3    (주)케이피케미칼   64420  2011/12  ...               5000.0  2013/01/15  4.916889e+11
4    현대하이스코(주)   10520  2011/12  ...               5000.0  2015/07/15  4.010000e+11
..         ...     ...      ...  ...                  ...         ...           ...
119    (주)삼양엔텍    8720  2011/12  ...               5000.0  2014/12/30  6.177600e+09
120    (주)동성화학    5190  2020/12  ...               1000.0  2021/04/16  5.335564e+09
121  (주)신성에프에이  104120  2011/12  ...                500.0  2017/01/02  4.407250e+09
122   (주)신성이엔지  104110  2011/12  ...                500.0  2017/01/02  4.407250e+09
123   케이비물산(주)    8540  2011/01  ...                500.0  2012/06/08  3.042917e+09

[124 rows x 8 columns]

In [ ]:
df_6=df_5.drop(['자산(*)(천원)'],axis=1)
df_6

           회사명   거래소코드     회계년도  ...  * 주당 액면가액(IFRS)(천원)       상장폐지일            시총
0      (주)한진해운  117930  2014/12  ...               5000.0  2017/03/07  1.226320e+12
1      두산건설(주)   11160  2012/12  ...               5000.0  2020/03/24  8.673351e+11
2      삼성물산(주)     830  2011/12  ...               5000.0  2015/09/15  8.043321e+11
3    (주)케이피케미칼   64420  2011/12  ...               5000.0  2013/01/15  4.916889e+11
4    현대하이스코(주)   10520  2011/12  ...               5000.0  2015/07/15  4.010000e+11
..         ...     ...      ...  ...                  ...         ...           ...
119    (주)삼양엔텍    8720  2011/12  ...               5000.0  2014/12/30  6.177600e+09
120    (주)동성화학    5190  2020/12  ...               1000.0  2021/04/16  5.335564e+09
121  (주)신성에프에이  104120  2011/12  ...                500.0  2017/01/02  4.407250e+09
122   (주)신성이엔지  104110  2011/12  ...                500.0  2017/01/02  4.407250e+09
123   케이비물산(주)    8540  2011/01  ...                500.0  2012/06/08  3.042917e+09

[124 rows x 7 columns]